config/routes.rb
Rails.application.routes.draw do

  get 'welcome/new'

  get 'welcome/index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :subject_group_books do 
    collection do
      get 'metadata_sheet'
      post 'import'
      post 'unassociate_books'
    end
  end
 mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
 
  get 'index_contents/content_code'

  get 'index_contents/publisher_code'

  get '/download_quote/:id', to: 'content_conversations#show', as: 'download_quote'

  get 'my_accounts/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :site_settings do 
    collection do 
      get 'books_of_publisher'
      get 'simple_search'
      get 'homepage'
      get 'new_homepage'
      patch 'update_homepage'
    end
  end

  get 'homes/index'
  root :to => "homes#index"
  get 'homes/search'
  get 'homes/subscribes_books'
  get 'homes/institution_edit'
  get 'homes/institution_profile_wta'

  resources :homes do
    collection do
      get  'permission_check_for_books'
      get  'books_by_category'
      get  'books_by_subject'
      get  'about'
      get  'terms_and_conditions'
      get  'policy'
      post 'wt_books_description' 
      get 'books_description'
      get 'wt_categories'
      get 'advance_search'
      get 'books_by_title'
      post 'send_mail'
      get 'refine_search'
      get 'refine_publishers_book'
      get 'refine_search_by_subject'
      get 'get_search_results'
      get 'get_author'
      get 'books_by_author'
      get 'contact'
      get 'catalogue'
      get 'download_file'
      get 'search'
      get 'sign_in'
      post 'login'
      get 'registration'
      post 'sign_up'
      delete 'logout'
      get 'current_user'
      get 'my_profile'
    end
  end

  resources :subject_groups do 
    collection do 
      get 'associate_book'
      get 'unassociate_book'
      post 'import'
      get 'metadata_sheet'
      get 'search'      
    end
  end 
 
  resources :contacts
  resources :subjects do
    collection do
      get 'search'
      post 'import'
      get 'metadata_sheet'
    end
  end

  resources :reports, :printhouse_setup, 
             only: [:index]
  resources :books_seo_config,:books_content_access_rules,
            :books_content_pricing, :books_contributors 
  resources :institution_accounts do
    collection do 
      get 'search'
      get 'add_subscription'
      post 'add_subscription_tag'
      get 'institution_admin_result'
      get 'metadata_for_institution_accounts'
      get 'metadata_for_institution_accounts_billing'
      get 'metadata_for_ip_address'
      post 'import_for_institution_accounts'
      post 'import_for_institution_accounts_billing'
      post 'import_for_ip_address'
    end
  end

  resources :library_users do 
    collection do
      get 'result'
    end
  end

  resources :articles do 
    collection do
      get 'search'
      get 'metadata_sheet'
    end
  end

  devise_for :users
  
  # devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'users/sign_in'

  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  resources :retailers do 
    collection do
      get 'search'
      get 'result'
    end
  end

  resources :end_users, :admin_users do 
    collection do
      get  'search' 
      get  'metadata_sheet'
      post 'import_for_end_users'
      # post 'create'
    end
  end

  resources :content_conversations do
    collection do 
      get 'content_history'
      get 'index_content'
      get 'qa_check'
      get 'update_status'
      get 'uploaded_errors'
      get 'dashboard'
      get 'download_books'
      get 'download_article'
      get 'download_update_status'
      get 'download_index_content'
      get 'download_subject_group'
    end
  end
  
  resources :subscriptions do
    collection do
      get 'view'
      post 'link'
      post 'save'
      get 'search'
      get 'content_search'
      get 'metadata_sheet'
      get 'search_result'
      get 'apply_discount'
      get 'result'
      get 'linked_member_publisher'
      get 'subject_group_search'
      get 'title_search'
      get 'associate_subscription_with_books'
      get 'associate_subscription_with_institutes'
      post 'import_for_subscription_institute'
      post 'import_for_subscription'
      post 'import'
    end
  end

  resources :publishers, :access_tokens, :promo_codes, :campaigns, :license_groups, :licenses,
            :subscriptions, :member_publishers do 
    collection do 
      post 'save'
      get 'search'
      get 'content_search'
      get 'metadata_sheet'
      get 'search_result'
      get 'apply_discount'
      get 'result'
      get 'linked_member_publisher'
      get 'subject_group_search'
      get 'title_search'
    end
  end
  
  resources :journals do
    collection do
      get 'index'
      get 'search'
      get 'search_result'  
    end
  end

  resources :books do
    collection do
      post 'save'
      get 'search'
      get 'metadata_sheet_for_books_primary_information'
      get 'metadata_sheet_for_books_contributor'
      get 'onix_input'
      get 'onix_supp_sheet'
      post 'import'
      post 'import_contributor'
      post 'import_chapter_details'
      delete 'destroy'
    end
  end

  resources :institution_admin_users do 
    collection do 
      get 'search'
    end
  end

  resources :themes do 
    collection do
      post 'save' 
      get 'change_theme'
      post 'save_theme_for_publisher'
      delete 'destroy'
    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	include Filterable
	belongs_to :instituion_account, optional: true
	has_many :subscription_books
	has_many :books_primary_content_informations, through: :subscription_books
	has_many :subject_groups, through: :subscription_books
	has_many :subscription_institute
    has_many :instituition_accounts, through: :subscription_institute
    validates_uniqueness_of :subscription_name
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def subject_group_search
    # search for the Subject Group at the time of Subject Group creation
    @subject_group_search = SubjectGroup.filter(params.slice(:subject_group_name, :subject_group_code))
  end

  def title_search
    # search for the Title at the time of Title creation
    isbn_book_info = params[:isbn].split
    if isbn_book_info.count == 1 || params[:book_title].present?
      @title_search = BooksPrimaryContentInformation.filter(params.slice(:isbn, :book_title, :file_name, :publication_year))
    else
      @title_search = BooksPrimaryContentInformation.where(isbn: isbn_book_info)
    end
  end

  def new
    @subscription = Subscription.new
  end

  def search
    @subscription = Subscription.filter(params.slice(:publisher_id, :subscription_name, :available_for_institutional_accounts, :subscription_category))
  end
  
  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.save! && params[:value] == "Subject Group"
      add_subscription_for_subject_group
      redirect_to subscriptions_path
    elsif @subscription.save! && params[:value] == "Book"
      add_subscription_for_book  
      redirect_to subscriptions_path
    else
      redirect_to new_subscription_path
    end
  end

  def edit
    @subscription  = Subscription.find(params[:id])
    render 'new'
  end
  
  def add_subscription_for_subject_group
    role_ids = params[:subscription][:role_ids]
    new_role_ids = []
    role_ids.each do |role_id|
      new_role_id = role_id.split(',').map(&:squish)
      new_role_ids << new_role_id
    end
    new_role_ids.flatten.each do |role_id|
      @subject_group_id = SubscriptionBook.new
      @subject_group_id.subscription_id = @subscription.id
      @subject_group_id.subject_group_id = role_id
      @subject_group_id.save!
    end
  end

  def add_subscription_for_book
    role_ids = params[:subscription][:role_ids]
    new_role_ids = []
    role_ids.each do |role_id|
      new_role_id = role_id.split(',').map(&:squish)
      new_role_ids << new_role_id
    end
    new_role_ids.flatten.each do |role_id|
      @book_id = SubscriptionBook.new
      @book_id.subscription_id = @subscription.id
      @book_id.books_primary_content_information_id = role_id
      @book_id.save!
    end
  end

  # def condition_one
  # end

  # def condition_two
  # end

  # def condition_three
  # end

  # def condition_four
  # end

  def index
    #Call filter method to get search results
    @subscription = Subscription.filter(params.slice(:publisher_id, :email, :last_name, :country_code))
  end

  def view
    @end_user_id = params[:end_user_id]
    @end_user_first_name = params[:end_user_first_name]
    @end_user_last_name = params[:end_user_last_name]
    @subscriptions = Subscription.all
  end

  def metadata_sheet
  end

  def associate_subscription_with_books
  end

  def import_for_subscription
    #  In this method,we get the entire Excel file in params.
    # in params[:file], we get the path of the excel file.
    spreadsheet = open_spreadsheet(params[:file])
    header = spreadsheet.row(1)
    # we fetch first row elements( that act as column names of table) in header
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      # we get excel's row elements(that are attributes of table) in header
      # and in spreadsheet.row(i) we get data for record
      # here we transpose inorder to map each column and data for record insertion
      @subscriptions = Subscription.new
      @subscriptions.attributes = row.to_hash.slice(*row.to_hash.keys)
      @subscriptions.save!
    end
    redirect_to :back
  end

  def import
    #  In this method,we get the entire Excel file in params.
    # in params[:file], we get the path of the excel file.
    spreadsheet = open_spreadsheet(params[:file])
    header = spreadsheet.row(1)
    # we fetch first row elements( that act as column names of table) in header
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      # we get excel's row elements(that are attributes of table) in header
      # and in spreadsheet.row(i) we get data for record
      # here we transpose inorder to map each column and data for record insertion
      @subscriptionbooks = SubscriptionBook.new
      @subscriptionbooks.attributes = row.to_hash.slice(*row.to_hash.keys)
      @subscriptionbooks.save!
    end
    redirect_to :back
  end

  def import_for_subscription_institute
    #  In this method,we get the entire Excel file in params.
    # in params[:file], we get the path of the excel file.
    spreadsheet = open_spreadsheet(params[:file])
    header = spreadsheet.row(1)
    # we fetch first row elements( that act as column names of table) in header
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      # we get excel's row elements(that are attributes of table) in header
      # and in spreadsheet.row(i) we get data for record
      # here we transpose inorder to map each column and data for record insertion
      @subscriptioninstitutes = SubscriptionInstitute.new
      @subscriptioninstitutes.attributes = row.to_hash.slice(*row.to_hash.keys)
      @subscriptioninstitutes.save!
    end
    redirect_to :back
  end

  def open_spreadsheet(file)
     #  the details of Excel sheet are holded in file
    case File.extname(file.original_filename)
      # in file.original_filename, we get the name of the excel sheet.
      #  the File.extname is a method that is used to fetch the extension 
      # of file
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Spreadsheet.open(file.path, extension: :xls)
     # in file.path,we get the path in which the excel sheet is stored
     # Roo:Spreadsheet.open(file.path, extension: :xls) helps us to open the 
     # Excel Spreadsheet
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  private
  def subscription_params
    params.require(:subscription).permit(:publisher_id, :subscription_id, 
    :subscription_name, :subscription_description, :subscription_category, 
    :subscription_type, :agreement_form, :agreement_to, :role_ids,
    :available_for_institutional_account, :purchase_information_price,
    :purchase_information_number_of_books, 
    :purchase_information_discount_percentage)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_result_subject_group.html.erb
<div class="col-md-12">
  <div class="mt10 table-demo"> Search Result 
    <span class="pull-right">
      <div class="dropdown">
        <ul class="nav">
          <li class="drop"><i style="cursor: pointer;width: 12px;" class="fa fa-ellipsis-v" aria-hidden="true"></i>
            <ul class="dropdown-menu-right">
              <li><a href="#"> <i class="fa fa-file-excel-o" aria-hidden="true"></i> Excel</a></li>
              <li><a href="#"> <i class="fa fa-file-word-o" aria-hidden="true"></i> Word</a></li>
              <li><a href="#"> <i class="fa fa-file-pdf-o" aria-hidden="true"></i> PDF</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </span> 
  </div>
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr style="font-size:13px" class="content_head">
          <th><input type="checkbox" name="select-all" id="select-all" /></th>
          <th>Subject Group Name  </th>
          <th> Subject Group Code </th>
          <th>Subject Group ID </th>
        </tr>
      </thead>
      <% if @subject_group_search.present? %>
        <% @subject_group_search.each do |sub_group| %>
          <tbody>
            <tr class="content_value">
              <td><input type="checkbox" name="checkbox" id="chk" /></td>
              <td><%= sub_group.subject_group_name %></td>
              <td><%= sub_group.subject_group_code %></td>
              <td><%= sub_group.id %></td>
            </tr>
          </tbody>
        <% end %>
        <div class="col-md-12 text-right">
          <input type="button" value="add" onclick="getAddDetails();" class="btn btn-sm" />
        </div>
      <%else%>
        No Record Found
      <%end%>
    </table>
  </div>
</div>

<script>
  $('#select-all').click(function(event) {   
    if(this.checked) {
      // Iterate each checkbox 
      $(':checkbox').each(function() {
          this.checked = true;                        
      });
    } else {
    $(':checkbox').each(function() {
      this.checked = false;                        
    });
  }
  });
  
  function getAddDetails(){   
   var srcrow = $('.content_value').has('input:checked');
   console.log(srcrow)
    var lastRow = srcrow.clone();
    lastRow.each(function(index, row){
      $(row).find('checked').each(function(idx, el){
          var el = $(el);
          el.val(srcrow.eq(index).find('select').eq(idx).val())
      });
    });
    $(".content_head").each(function(i, el) {
      $(this).closest('.content_head').clone().removeClass('content_head').addClass('clone_content_head').insertBefore(".content_value:first");
    });
    $('.clone_content_head').find('td:last').after('<td class="tableheader">Delete</td>');
    var cloned =lastRow.closest('.content_value').clone().removeClass('content_value').addClass('clone_content_value').insertAfter(".clone_content_head:last");
    var arr = []
    lastRow.closest('.content_value').find("td:last").each(function(){
      arr.push($(this).text())
    });

    $('#role_ids').val(arr)
    $('.clone_content_value').find('td:last').after('<td class = "del"><%= image_tag("delete_icon.gif")%></td>');
    $(':checkbox').each(function() {
      $('#select-all').remove();
      $("#chk").remove(); 
      $(".btn btn-sm").remove()                      
    });
           $('.content_value').remove();
   $('.content_head').remove();
   $('.btn btn-sm').show();
    
   $('.del').on('click',function(){
    $(this).parent().remove();
    arr.pop($(this).text())
      $('#role_ids').val(arr)
   });
   }
</script>

app/views/subscriptions/_result_title.html.erb
<div class="col-md-12">
  <div class="mt10 table-demo">Search Result 
    <span class="pull-right">
      <div class="dropdown">
        <ul class="nav">
          <li class="drop"><i style="cursor: pointer;width: 12px;" class="fa fa-ellipsis-v" aria-hidden="true"></i>
            <ul class="dropdown-menu-right">
              <li><a href="#"> <i class="fa fa-file-excel-o" aria-hidden="true"></i> Excel</a></li>
              <li><a href="#"> <i class="fa fa-file-o" aria-hidden="true"></i> CSV</a></li>
              <li><a href="#"> <i class="fa fa-file-pdf-o" aria-hidden="true"></i> PDF</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </span>
  </div>
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr style="font-size:13px" class="content_head">
          <th><input type="checkbox" name="select-all" id="select-all" /></th>
          <th>Title</th>
          <th>Content Identifier</th>
          <th>Title ID</th>
        </tr>
      </thead>
      <tbody>
        <% if @title_search.present? %>
          <% @title_search.each do |title_group| %>
            <tr class="content_value">
              <td><input type="checkbox" name="checkbox" id="chk" /></td>
              <td><%= title_group.book_title %></td>
              <td><%= title_group.isbn %></td>
              <td><%= title_group.id %></td>
            </tr>
          <% end %>
          <tr>
            <td>&nbsp;</td>
            <td><input type="button" value="add" onclick="getAddDetails();" class="btn btn-sm" /></td>
          </tr>
        <%else%>
          No Record Found
        <%end%>
      </tbody>
    </table>
  </div>
</div>
<div class="col-sm-12"></div>

<script>
  $('#select-all').click(function(event) {   
    if(this.checked) {
      // Iterate each checkbox 
      $(':checkbox').each(function() {
          this.checked = true;                        
      });
    } else {
    $(':checkbox').each(function() {
      this.checked = false;                        
    });
  }
  });
  
  function getAddDetails(){   
   var srcrow = $('.content_value').has('input:checked');
   console.log(srcrow)
    var lastRow = srcrow.clone();
    lastRow.each(function(index, row){
      $(row).find('checked').each(function(idx, el){
          var el = $(el);
          el.val(srcrow.eq(index).find('select').eq(idx).val())
      });
    });
    $(".content_head").each(function(i, el) {
      $(this).closest('.content_head').clone().removeClass('content_head').addClass('clone_content_head').insertBefore(".content_value:first");
    });
    $('.clone_content_head').find('td:last').after('<td class="tableheader">Delete</td>');
    var cloned =lastRow.closest('.content_value').clone().removeClass('content_value').addClass('clone_content_value').insertAfter(".clone_content_head:last");
    var arr = []
    lastRow.closest('.content_value').find("td:last").each(function(){
      arr.push($(this).text())
    });

    $('#role_ids').val(arr)
    $('.clone_content_value').find('td:last').after('<td class = "del"><%= image_tag("delete_icon.gif")%></td>');
    $(':checkbox').each(function() {
      $('#select-all').remove();
      $("#chk").remove(); 
      $(".btn btn-sm").remove()                      
    });
           $('.content_value').remove();
   $('.content_head').remove();
   $('.btn btn-sm').show();
    
   $('.del').on('click',function(){
    $(this).parent().remove();
    arr.pop($(this).text())
      $('#role_ids').val(arr)
   });
   }
</script>

app/views/subscriptions/_search_subject_group.html.erb
<div class="col-md-12">
  <div class="form-bg">
    <div class="col-md-5">
      <label>Subject Group Name</label>
      <input id="subject_group_name" type="text" placeholder="Subject Group Name" class="form-control">
    </div>
    <div class="col-md-5">
      <label>Subject Group Code</label>
      <input id="subject_group_code" type="text" placeholder="Subject Group Code" class="form-control">
    </div>
    <div class="col-md-2">
      <label> &nbsp;</label>
      <input type="button" name="button2" id="button" value="Search" onclick="getSearchDetails1();" class="btn btn-sm" />
    </div>
    <div class="clearfix"></div>
  </div>
</div>

<script type="text/javascript">
  function getSearchDetails1(){
    var subject_group_name = $('#subject_group_name').val();
    var subject_group_code = $('#subject_group_code').val();
    $.ajax({
      type: 'GET',
      url: '/subscriptions/subject_group_search',
      data : { subject_group_name: subject_group_name,subject_group_code: subject_group_code }
    });
  }
</script>

app/views/subscriptions/associate_subscription_with_books.html.erb
<!doctype html>
<html>
<head>
<title>Content Store </title>
<!-- Latest compiled and minified CSS -->
  <!-- Header -->
  <%= render :partial => "layouts/top_header"%>
  <!-- Header Ends --> 
</head>

<body>
<!-- Aside Start-->
  <%= render :partial => "layouts/sidebar"%>
    <!-- Aside Ends-->
<!--Main Content Start -->
  <section class="content"> 
    <!-- Page Content Start --> 
    <!-- ================== -->
    <div class="container-fluid">
      <ol class="breadcrumb">
           <li><a>Home</a></li>
         <li><a>Manage Access</a></li>
         <li><a>Subscription</a></li>
         <li><a>Upload Metadata Sheet for Associating Subscription with Books</a></li>
      </ol>

      <h2 class="H2-L1">Upload Metadata Sheet for Associating Subscription with Books</h2>
      <%= form_tag import_subscriptions_path, multipart: true do %>
        <div class="col-md-6">
          <div class="form-group">
            <label for="bookISBN" class="col-sm-4 nopadding">Browse File</label>
            <span class="col-sm-8">
            <%= file_field_tag :file, :required => true, :class => "form-control", :placeholder =>"Browse files" %>
            </span> 
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="clearfix m-b-30"></div>
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 colx-12 text-right">

            <%= button_tag fa_icon("fa fa-plus-square-o", text: "Import"), :class => "btn btn-sm", type: :submit %>

            <%= button_tag fa_icon("refresh", text: "Reset"), :class => "btn btn-sm" ,type: :reset%>

          </div>
        </div>
      <% end %>

    </div>  
    <!-- Footer Start -->
    <%= render :partial => "layouts/footer" %>
    <!-- Footer Ends --> 
  </section>
</body>
</html>

app/views/subscriptions/associate_subscription_with_institutes.html.erb
<!doctype html>
<html>
<head>
<title>Content Store </title>
<!-- Latest compiled and minified CSS -->
  <!-- Header -->
  <%= render :partial => "layouts/top_header"%>
  <!-- Header Ends --> 
</head>

<body>
<!-- Aside Start-->
  <%= render :partial => "layouts/sidebar"%>
    <!-- Aside Ends-->
<!--Main Content Start -->
  <section class="content"> 
    <!-- Page Content Start --> 
    <!-- ================== -->
    <div class="container-fluid">
      <ol class="breadcrumb">
           <li><a>Home</a></li>
         <li><a>Manage Access</a></li>
         <li><a>Subscription</a></li>
         <li><a>Metadata Sheet for Associating Subscription with Institute</a></li>
      </ol>

      <h2 class="H2-L1">Metadata Sheet for Associating Subscription with Institute</h2>
      <%= form_tag import_for_subscription_institute_subscriptions_path, multipart: true do %>
        <div class="col-md-6">
          <div class="form-group">
            <label for="bookISBN" class="col-sm-4 nopadding">Browse File</label>
            <span class="col-sm-8">
            <%= file_field_tag :file, :required => true, :class => "form-control", :placeholder =>"Browse files" %>
            </span> 
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="clearfix m-b-30"></div>
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 colx-12 text-right">

            <%= button_tag fa_icon("fa fa-plus-square-o", text: "Import"), :class => "btn btn-sm", type: :submit %>

            <%= button_tag fa_icon("refresh", text: "Reset"), :class => "btn btn-sm" ,type: :reset%>

          </div>
        </div>
      <% end %>

    </div>  
    <!-- Footer Start -->
    <%= render :partial => "layouts/footer" %>
    <!-- Footer Ends --> 
  </section>
</body>
</html>

app/views/subscriptions/create.html.erb
Create

app/views/subscriptions/metadata_sheet.html.erb
<!doctype html>
<html>
<head>
<title>Content Store </title>
<!-- Latest compiled and minified CSS -->
  <!-- Header -->
  <%= render :partial => "layouts/top_header"%>
  <!-- Header Ends --> 
</head>

<body>
<!-- Aside Start-->
  <%= render :partial => "layouts/sidebar"%>
    <!-- Aside Ends-->
<!--Main Content Start -->
  <section class="content"> 
    <!-- Page Content Start --> 
    <!-- ================== -->
    <div class="container-fluid">
      <ol class="breadcrumb">
           <li><a>Home</a></li>
         <li><a>Manage Access</a></li>
         <li><a>Subscription</a></li>
         <li><a>Metadata Sheet for Subscription</a></li>
      </ol>

      <h2 class="H2-L1">Metadata Sheet for Subscription</h2>
      <%= form_tag import_for_subscription_subscriptions_path, multipart: true do %>
        <div class="col-md-6">
          <div class="form-group">
            <label for="bookISBN" class="col-sm-4 nopadding">Browse File</label>
            <span class="col-sm-8">
            <%= file_field_tag :file, :required => true, :class => "form-control", :placeholder =>"Browse files" %>
            </span> 
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="clearfix m-b-30"></div>
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 colx-12 text-right">

            <%= button_tag fa_icon("fa fa-plus-square-o", text: "Import"), :class => "btn btn-sm", type: :submit %>

            <%= button_tag fa_icon("refresh", text: "Reset"), :class => "btn btn-sm" ,type: :reset%>

          </div>
        </div>
      <% end %>

    </div>  
    <!-- Footer Start -->
    <%= render :partial => "layouts/footer" %>
    <!-- Footer Ends --> 
  </section>
</body>
</html>

app/views/subscriptions/search.js.erb
$("#search_result").html("<%= escape_javascript(render(:partial => "search_result", :object => @subject))%>");

app/views/subscriptions/view.html.erb
<!doctype html>
<html>
<head>
<title>Content Store :: Search Subject</title>
<!-- Latest compiled and minified CSS -->
    <!-- Header -->
   <%= render :partial => "layouts/top_header"%>
    <!-- Header Ends --> 
</head>

<body>
  <!-- Aside Start-->
    <%= render :partial => "layouts/sidebar"%>
    <!-- Aside Ends-->
  <!--Main Content Start -->
  <section class="content"> 
    <!-- Page Content Start --> 
    <!-- ================== -->
    <div class="wrapper container-fluid">
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a>Publisher Setup</a></li>
        <li><a>Associate Subscriptions</a></li>
      </ol>
      
      <h2 class="H2-L1">Associate Subscriptions</h2>
      <div class="wrapper container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="mt10 table-demo">
              Select Subscription for "<%= @end_user_first_name+" "+ @end_user_last_name %>"
            </div>
            <div class="table-responsive">
              <%= form_tag subject_group_books_path, :method => 'post' do %>
                <table class="table table-bordered">
                  <thead>
                    <tr style="font-size:13px">
                      <th></th>
                      <th>Subscription Name</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% if @subscriptions.present? %>
                      <% @subscriptions.each do |subscription| %>
                        <tr>
                          <td><%= check_box_tag "subscription_id[]", subscription.id %></td>
                          <td><%= subscription.subscription_name %></td>
                        </tr>
<!--                         <%= hidden_field_tag "subject_group_id", @subject_group_id %>
 -->                      <% end %>
                    <% else %>
                      <tr>
                        <td bgcolor="#FBFBFB">
                          <p> Record Not Found </p> 
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <%= button_tag fa_icon("search", text: "Associate Books"), :class => "btn btn-sm", type: :submit %>
              <% end %>
            </div>
          </div>
          <div class="col-sm-12"></div>
        </div>
      </div>
    </div>  
    <!-- Footer Start -->
    <%= render :partial => "layouts/footer" %>
    <!-- Footer Ends --> 
  </section>
</body>
</html>