config/routes.rb
Rails.application.routes.draw do

  get 'welcome/new'

  get 'welcome/index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :subject_group_books do 
    collection do
      get 'metadata_sheet'
      post 'import'
      post 'unassociate_books'
    end
  end
 mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
 
  get 'index_contents/content_code'

  get 'index_contents/publisher_code'

  get '/download_quote/:id', to: 'content_conversations#show', as: 'download_quote'

  get 'my_accounts/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :site_settings do 
    collection do 
      get 'books_of_publisher'
      get 'simple_search'
      get 'homepage'
      get 'new_homepage'
      patch 'update_homepage'
    end
  end

  get 'homes/index'
  root :to => "homes#index"
  get 'homes/search'
  get 'homes/subscribes_books'
  get 'homes/institution_edit'
  get 'homes/institution_profile_wta'

  resources :homes do
    collection do
      get  'permission_check_for_books'
      get  'books_by_category'
      get  'books_by_subject'
      get  'about'
      get  'terms_and_conditions'
      get  'policy'
      post 'wt_books_description' 
      get 'books_description'
      get 'wt_categories'
      get 'advance_search'
      get 'books_by_title'
      post 'send_mail'
      get 'refine_search'
      get 'refine_publishers_book'
      get 'refine_search_by_subject'
      get 'get_search_results'
      get 'get_author'
      get 'books_by_author'
      get 'contact'
      get 'catalogue'
      get 'download_file'
      get 'search'
      get 'sign_in'
      post 'login'
      get 'registration'
      post 'sign_up'
      delete 'logout'
      get 'current_user'
      get 'my_profile'
    end
  end

  resources :subject_groups do 
    collection do 
      get 'associate_book'
      get 'unassociate_book'
      post 'import'
      get 'metadata_sheet'
      get 'search'      
    end
  end 
 
  resources :contacts
  resources :subjects do
    collection do
      get 'search'
      post 'import'
      get 'metadata_sheet'
    end
  end

  resources :reports, :printhouse_setup, 
             only: [:index]
  resources :books_seo_config,:books_content_access_rules,
            :books_content_pricing, :books_contributors 
  resources :institution_accounts do
    collection do 
      get 'search'
      get 'add_subscription'
      post 'add_subscription_tag'
      get 'institution_admin_result'
      get 'metadata_for_institution_accounts'
      get 'metadata_for_institution_accounts_billing'
      get 'metadata_for_ip_address'
      post 'import_for_institution_accounts'
      post 'import_for_institution_accounts_billing'
      post 'import_for_ip_address'
    end
  end

  resources :library_users do 
    collection do
      get 'result'
    end
  end

  resources :articles do 
    collection do
      get 'search'
      get 'metadata_sheet'
    end
  end

  devise_for :users
  
  # devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'users/sign_in'

  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  resources :retailers do 
    collection do
      get 'search'
      get 'result'
    end
  end

  resources :end_users, :admin_users do 
    collection do
      get  'search' 
      get  'metadata_sheet'
      post 'import_for_end_users'
      # post 'create'
    end
  end

  resources :content_conversations do
    collection do 
      get 'content_history'
      get 'index_content'
      get 'qa_check'
      get 'update_status'
      get 'uploaded_errors'
      get 'dashboard'
      get 'download_books'
      get 'download_article'
      get 'download_update_status'
      get 'download_index_content'
      get 'download_subject_group'
    end
  end
  
  resources :subscriptions do
    collection do
      get 'view'
      post 'link'
      post 'save'
      get 'search'
      get 'content_search'
      get 'metadata_sheet'
      get 'search_result'
      get 'apply_discount'
      get 'result'
      get 'linked_member_publisher'
      get 'subject_group_search'
      get 'title_search'
      get 'associate_subscription_with_books'
      get 'associate_subscription_with_institutes'
      post 'import_for_subscription_institute'
      post 'import_for_subscription'
      post 'import'
    end
  end

  resources :publishers, :access_tokens, :promo_codes, :campaigns, :license_groups, :licenses,
            :subscriptions, :member_publishers do 
    collection do 
      post 'save'
      get 'search'
      get 'content_search'
      get 'metadata_sheet'
      get 'search_result'
      get 'apply_discount'
      get 'result'
      get 'linked_member_publisher'
      get 'subject_group_search'
      get 'title_search'
    end
  end
  
  resources :journals do
    collection do
      get 'index'
      get 'search'
      get 'search_result'  
    end
  end

  resources :books do
    collection do
      post 'save'
      get 'search'
      get 'metadata_sheet_for_books_primary_information'
      get 'metadata_sheet_for_books_contributor'
      get 'onix_input'
      get 'onix_supp_sheet'
      post 'import'
      post 'import_contributor'
      post 'import_chapter_details'
      delete 'destroy'
    end
  end

  resources :institution_admin_users do 
    collection do 
      get 'search'
    end
  end

  resources :themes do 
    collection do
      post 'save' 
      get 'change_theme'
      post 'save_theme_for_publisher'
      delete 'destroy'
    end
  end
end

app/views/shared/wtbooks/about.html.erb
<%= render :partial => "#{@publisher.theme_name}"%> 

<div class="container-fluid">
  <div class="row">
    <%= render :partial => "wtbooks_subject_sidebar"%>
    <div id='pub_book'>  
      <div class="col-sm-8 col-md-9">
        <ul class="breadcrumb breadcrumb2 print">
    		  <%= link_to "Home", homes_path%> &gt; ABOUT US 
        </ul>     
        <div class="border_wrapper padding10px">
          <div class="">
            <h1 class="text_uppercase border_bottom heading-main ">About Us</h1>
          </div>
          <% if @publisher_about.present? %>
            <p class="mt20"><%= @publisher_about.html_safe %></p>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render :partial => "homes/wtbooks_footer"%>

app/views/shared/wtbooks/books_by_author.html.erb
<%= render :partial => "#{@publisher.theme_name}"%> 

<div class="container-fluid">
  <div class="row">
    <%= render :partial => "wtbooks_subject_sidebar"%>
    <div id='pub_book'>  
    <div class="col-sm-8 col-md-9">
      <ul class="breadcrumb breadcrumb2 print">
        <%= link_to "Home", homes_path%> &gt; Browse by Author 
      </ul>
      <div class="border_wrapper padding10px">
        <div class="row ">
          <div class="col-sm-4 pb-10 ">Search Results</div>
          <div class="text-right col-sm-8">
            <%= form_tag  refine_publishers_book_homes_path, :method => 'get',:id=>"Author Name/Book Title",:class=>"form-inline", :remote => true do %>
              <div class="form-group">
                <%= text_field_tag :book_title,"", :class => "form-control", :placeholder => "Refine Search" %>
                <%= hidden_field_tag "book_ids", @ids  %>
              </div>
              <%= button_tag fa_icon("search", text: "Search"), :class => "btn btn-inverse", type: :submit %>
            <%end%>
          </div>
          <div class="col-md-12 col-xs-12 mt-20">
            <% if @books.count >= 0 %>
              <div class="bg-gray">
                <div class="col-sm-4 no-pad" style="padding-top: 6px;">
                  <%= page_entries_info @books %>
                </div>
                <div class="col-sm-8 text-right no-pad">
                  <nav aria-label="Page navigation">
                    <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                  </nav>
                </div>
                <div class="clearfix"></div>
              </div>
            <% end %>
          </div>
          <div class="clearfix"></div>
          <% if @books.present? %>
            <% @books.each do |f| %>
              <div class="col-md-12  no-pad mt-20">
                <div class="col-sm-2 col-xs-12 ">
                  <div class="effects search-result ">
                    <%= link_to image_tag("http://ebooks.#{@publisher.domain_name}.com/static/templates/template1/#{@publisher.publisher_code}/thumbnails/#{f.isbn}-T-FC.jpg",class: "img-responsive"), books_description_homes_path(:book_id => f.id), class: "cover2" %>
                  </div>
                </div>
                <div class="col-md-9">
                  <h2 title="<%= f.book_title.presence || "" %>">
                    <%= link_to f.book_title.presence || "", books_description_homes_path(:book_id => f.id) %>
                  </h2>
                  <h3 title="<%= (f.books_contributors.first.first_name.presence || "")+" "+(f.books_contributors.first.last_name.presence || "") %>">By :
                    <span class="dark_yellow">
                      <% f.books_contributors.each do |book_contributor| %>
                        <%= truncate(book_contributor.first_name.presence || "" +" "+book_contributor.last_name.presence || "", length: 14)%>
                      <%end%>
                    </span>
                  </h3>
                  <p><strong> Description :</strong>
                    <%= truncate(f.book_blurb.presence || "", length: 182) %>
                    <%= link_to 'more', '', :class => "read-more-#{f.id}" %>
                    <script>
                      $('.read-more-<%= f.id %>').on('click', function(e) {
                        e.preventDefault()
                      $(this).parent().html('<strong> Description:</strong> <%= f.book_blurb %>')
                      })
                    </script>
                  </p>
                  <p class="searchResultsLinks"><%= link_to "Book Info", books_description_homes_path(:book_id => f.id) %></p>
                </div>
              </div>
              <div class="col-md-12 ">
                <div class="border_bottom-list"> </div>
              </div>
            <% end %>
          <%else%>
            <div class="container">
              <div class="col-md-12">
                <h3> Record Not Found </h3>
              </div>
            </div>
          <%end%>
          <div class="col-md-12 col-xs-12 mt-20">
            <% if @books.count >= 0 %>
              <div class="bg-gray">
                <div class="col-sm-4 no-pad" style="padding-top: 6px;">
                  <%= page_entries_info @books %>
                </div>
                <div class="col-sm-8 text-right no-pad">
                  <nav aria-label="Page navigation" style="clear:both; height: 30px;">
                    <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                  </nav>
                </div>
                <div class="clearfix"></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
<%= render :partial => "homes/wtbooks_footer"%>

app/views/shared/wtbooks/books_by_category.html.erb
<%= render :partial => "#{@publisher.theme_name}"%> 

<div class="container-fluid">
  <div class="row">
    <%= render :partial => "wtbooks_subject_sidebar"%>
    <div id='pub_book'>  
    <div class="col-sm-8 col-md-9">
      <ul class="breadcrumb breadcrumb2 print">
        <%= link_to "Home", homes_path%> &gt; Browse by Categories 
      </ul>
      <div class="border_wrapper padding10px">
        <div class="row ">
          <div class="col-sm-4 pb-10 ">Search Results</div>
          <div class="text-right col-sm-8">
            <%= form_tag  refine_publishers_book_homes_path, :method => 'get',:id=>"Author Name/Book Title",:class=>"form-inline", :remote => true do %>
              <div class="form-group">
                <%= text_field_tag :book_title,"", :class => "form-control", :placeholder => "Refine Search" %>
                <%= hidden_field_tag "book_ids", @ids  %>
              </div>
              <%= button_tag fa_icon("search", text: "Search"), :class => "btn btn-inverse", type: :submit %>
            <%end%>
          </div>
          <div class="col-md-12 col-xs-12 mt-20">
            <% if @books.count >= 0 %>
              <div class="bg-gray">
                <div class="col-sm-4 no-pad" style="padding-top: 6px;">
                  <%= page_entries_info @books %>
                </div>
                <div class="col-sm-8 text-right no-pad">
                  <nav aria-label="Page navigation">
                    <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                  </nav>
                </div>
                <div class="clearfix"></div>
              </div>
            <% end %>
          </div>
          <div class="clearfix"></div>
          <% if @books.present? %>
            <% @books.each do |f| %>
              <div class="col-md-12  no-pad mt-20">
                <div class="col-sm-2 col-xs-12 ">
                  <div class="effects search-result ">
                    <%= link_to image_tag("http://ebooks.#{@publisher.domain_name}.com/static/templates/template1/#{@publisher.publisher_code}/thumbnails/#{f.isbn}-T-FC.jpg",class: "img-responsive"), books_description_homes_path(:book_id => f.id), class: "cover2" %>
                  </div>
                </div>
                <div class="col-md-9">
                  <h2 title="<%= f.book_title.presence || "" %>">
                    <%= link_to f.book_title.presence || "", books_description_homes_path(:book_id => f.id) %>
                  </h2>
                  <h3 title="<%= (f.books_contributors.first.first_name.presence || "")+" "+(f.books_contributors.first.last_name.presence || "") %>">By :
                    <span class="dark_yellow">
                      <% f.books_contributors.each do |book_contributor| %>
                        <%= book_contributor.first_name.presence || ""%>&nbsp<%= book_contributor.last_name.presence || ""%>
                      <%end%>
                    </span>
                  </h3>
                  <p><strong> Description :</strong>
                    <%= truncate(f.book_blurb.presence || "", length: 182) %>
                    <%= link_to 'more', '', :class => "read-more-#{f.id}" %>
                    <script>
                      $('.read-more-<%= f.id %>').on('click', function(e) {
                        e.preventDefault()
                      $(this).parent().html('<strong> Description:</strong> <%= f.book_blurb %>')
                      })
                    </script>
                  </p>
                  <p class="searchResultsLinks"><%= link_to "Book Info", books_description_homes_path(:book_id => f.id) %></p>
                </div>
              </div>
              <div class="col-md-12 ">
                <div class="border_bottom-list"> </div>
              </div>
            <% end %>
          <%else%>
            <div class="container">
              <div class="col-md-12">
                <h3> Record Not Found </h3>
              </div>
            </div>
          <%end%>
          <div class="col-md-12 col-xs-12 mt-20">
            <% if @books.count >= 0 %>
              <div class="bg-gray">
                <div class="col-sm-4 no-pad" style="padding-top: 6px;">
                  <%= page_entries_info @books %>
                </div>
                <div class="col-sm-8 text-right no-pad">
                  <nav aria-label="Page navigation" style="clear:both; height: 30px;">
                    <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                  </nav>
                </div>
                <div class="clearfix"></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
<%= render :partial => "homes/wtbooks_footer"%>

app/views/shared/wtbooks/books_by_subject.html.erb
<%= render :partial => "#{@publisher.theme_name}"%> 

<div class="container-fluid">
  <div class="row">
    <%= render :partial => "wtbooks_subject_sidebar"%>
    <div id='pub_book'>  
    <div class="col-sm-8 col-md-9">
      <ul class="breadcrumb breadcrumb2 print">
        <%= link_to "Home", homes_path%> &gt; Browse by Categories 
      </ul>
      <div class="border_wrapper padding10px">
        <div class="row ">
          <div class="col-sm-4 pb-10 ">Search Results</div>
          <div class="text-right col-sm-8">
            <%= form_tag  refine_publishers_book_homes_path, :method => 'get',:id=>"Author Name/Book Title",:class=>"form-inline", :remote => true do %>
              <div class="form-group">
                <%= text_field_tag :book_title,"", :class => "form-control", :placeholder => "Refine Search" %>
                <%= hidden_field_tag "book_ids", @ids  %>
              </div>
              <%= button_tag fa_icon("search", text: "Search"), :class => "btn btn-inverse", type: :submit %>
            <%end%>
          </div>
          <div class="col-md-12 col-xs-12 mt-20">
            <% if @books.count >= 0 %>
              <div class="bg-gray">
                <div class="col-sm-4 no-pad" style="padding-top: 6px;">
                  <%= page_entries_info @books %>
                </div>
                <div class="col-sm-8 text-right no-pad">
                  <nav aria-label="Page navigation">
                    <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                  </nav>
                </div>
                <div class="clearfix"></div>
              </div>
            <% end %>
          </div>
          <div class="clearfix"></div>
          <% if @books.present? %>
            <% @books.flatten.each do |f| %>
              <div class="col-md-12  no-pad mt-20">
                <div class="col-sm-2 col-xs-12 ">
                  <div class="effects search-result ">
                    <%= link_to image_tag("http://ebooks.#{@publisher.domain_name}.com/static/templates/template1/#{@publisher.publisher_code}/thumbnails/#{f.isbn}-T-FC.jpg",class: "img-responsive"), books_description_homes_path(:book_id => f.id), class: "cover2" %>
                  </div>
                </div>
                <div class="col-md-9">
                  <h2 title="<%= f.book_title.presence || "" %>">
                    <%= link_to f.book_title.presence || "", books_description_homes_path(:book_id => f.id) %>
                  </h2>
                  <% f.books_contributors.limit(1).each do |book_contributor| %>
                    <h3 title="<%= (book_contributor.first_name.presence || "") +" "+(book_contributor.last_name.presence || "") %>">By :
                      <span class="dark_yellow">
                        <% f.books_contributors.each do |book_contributor| %>
                          <%= book_contributor.first_name.presence || ""%>&nbsp<%= book_contributor.last_name.presence || ""%>
                        <%end%>
                      </span>
                    </h3>
                  <%end%>
                  <p><strong> Description :</strong>
                    <%= truncate(f.book_blurb.presence || "", length: 182) %>
                    <%= link_to 'more', '', :class => "read-more-#{f.id}" %>
                    <script>
                      $('.read-more-<%= f.id %>').on('click', function(e) {
                        e.preventDefault()
                      $(this).parent().html('<strong> Description:</strong> <%= f.book_blurb %>')
                      })
                    </script>
                  </p>
                  <p class="searchResultsLinks"><%= link_to "Book Info", books_description_homes_path(:book_id => f.id) %></p>
                </div>
              </div>
              <div class="col-md-12 ">
                <div class="border_bottom-list"> </div>
              </div>
            <% end %>
          <%else%>
            <div class="container">
              <div class="col-md-12">
                <h3> Record Not Found </h3>
              </div>
            </div>
          <%end%>
          <div class="col-md-12 col-xs-12 mt-20">
            <% if @books.count >= 0 %>
              <div class="bg-gray">
                <div class="col-sm-4 no-pad" style="padding-top: 6px;">
                  <%= page_entries_info @books %>
                </div>
                <div class="col-sm-8 text-right no-pad">
                  <nav aria-label="Page navigation" style="clear:both; height: 30px;">
                    <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                  </nav>
                </div>
                <div class="clearfix"></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
<%= render :partial => "homes/wtbooks_footer"%>

app/views/shared/wtbooks/contact.html.erb
<%= render :partial => "#{@publisher.theme_name}"%>

<div class="container-fluid">
  <div class="row">
    <%= render :partial => "wtbooks_subject_sidebar"%>
    <div id='pub_book'>  
    <div class="col-sm-8 col-md-9">
      <ul class="breadcrumb breadcrumb2 print">
        <%= link_to "Home", homes_path%> &gt; Contact Us
      </ul>
      <div class="border_wrapper padding10px">
        <div class="">
          <h1 class="text_uppercase border_bottom heading-main text-uppercase "> Contact Us</h1>
        </div>
       
        <%= form_tag send_mail_homes_path , :class => "form-horizontal" do %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        
          <div class=" col-sm-12 grayContainer pad20">
            <div class="col-sm-12">
              <p>Please select one of the following message options before you write your message to ensure we can answer your question as quickly as possible:</p>
              <div class="mt20" style="padding:20px"> 
                <%= radio_button_tag 'theme', 'I have a general comment about this site', true %> I have a general comment about this site
                <br><%= radio_button_tag 'theme', 'I have editorial/content related feedback for the publisher' %> I have editorial/content related feedback for the publisher
                <br><%= radio_button_tag 'theme', 'I would like technical support from the Help Desk' %> I would like technical support from the Help Desk
                <br><%= radio_button_tag 'theme', 'I see a problem with this page' %> I see a problem with this page
    				  </div>
            </div>
            <div class="clearfix "></div>
            <hr>
            <div class="col-sm-8">
              <p><em>Fields marked with <sup class="mandatory">*</sup>are compulsory</em></p><br> 
              <fieldset>
                <div class="form-group  ">
                  <label class="col-md-3 control-label" for=""> Your name: <sup class="mandatory">*</sup></label>
                  <div class="col-md-7">
                    <%= text_field_tag :name,"", :class => "form-control" %>
                  </div>
                </div>
                <div class="form-group  mt-20">
                  <label class="col-md-3 control-label" for=""> Your email: <sup class="mandatory">*</sup></label>
                  <div class="col-md-7">
                    <%= text_field_tag :email,"", :required => true ,:class => "form-control" %>
                  </div>
                </div>
                <div class="form-group  mt-20">
                  <label class="col-md-3 control-label" for=""> Subject:</label>
                  <div class="col-md-7">
                    <%= text_field_tag :subject,"", :class => "form-control" %>
                  </div>
                </div>
                <div class="form-group  mt-20">
                  <label class="col-md-3 control-label" for=""> Your message: <sup class="mandatory">*</sup></label>
                  <div class="col-md-7">
                    <%= text_area_tag :message,"", :class => "form-control", :style => "resize:none;", :maxlength => "140", :rows => "7" %>
                  </div>
                </div>
                <div class="form-group  mt-20">
                  <label class="col-md-3" for=""></label>
                  <div class="col-md-7">
                    <label style="padding-left:20px" class="checkbox"><input type="checkbox" name="sendToMyEmailId" value="on">Please send a copy of this message to my email address. </label>
                  </div>
                </div>
                <div>
                  <label class="col-md-3" for=""></label>
                  <div class="col-md-7 " style="padding-left: 5px;">
                    <input type="submit" name="submit" value="Send Message" class="btn btn-small btn-inverse" style="">
                  </div>
                </div>
              </fieldset>
            </div>
          </div>
        <% end %>
        <div class="clearfix"></div>
        <div class="mt10">
          <h1 class="text_uppercase border_bottom heading-main text-uppercase "></h1>
          <div class="col-md-3">
            <h4>Office Address</h4>
            <p><%= @publisher.publisher_address.presence || "" %>
            </p>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
<%= render :partial => "homes/wtbooks_footer"%>

app/views/shared/wtbooks/get_author.html.erb
<%= render :partial => "#{@publisher.theme_name}"%> 
<% if ip_logged_in? %>
    <div class="container-fluid">
      <div class="row">
        <%= render :partial => "wtbooks_subject_sidebar"%>
        <div id='pub_book'>  
        <div class="col-sm-8 col-md-9">
          <ul class="breadcrumb breadcrumb2 print">
            <%= link_to "Home", homes_path%> &gt; Authors
          </ul>
          <div class="border_wrapper padding10px">
            <div class="">
              <h1 class="text_uppercase border_bottom heading-main text-uppercase "> AUTHOR(S):</h1>
            </div>       
            <div class="text_uppercase  border_bottom padding_bottom12px">
              <div class="col-sm-12 no-padd">
                <div class="ln-letters">
                  <ul class="abc nomargin">
                    <% ('A'..'Z').each do |letter| %> 
                      <li>
                        <%= link_to letter, get_author_homes_path(:letter=>letter, institution_id: params[:institution_id])%>
                      </li>
                    <%end%>
                  </ul>
                  <div class="clearfix ln-last"></div>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
            <%if @authors.present?%>
              <%@authors.each do |authname| %>
                <div class="col-md-12 no-padd">
                  <ul id="demoOne" class="description margin_left5px">
                    <li class="ln-K ln-k"><%= link_to truncate(authname, length: 14), books_by_author_homes_path(authname, institution_id: params[:institution_id]) %>
                    </li>
                  </ul>
                </div>
              <%end%> 
            <%end%>
          </div>
        </div>
        </div>
      </div>
    </div>
    <%= render :partial => "homes/publisher_footer"%>
<% else %>
  <div class="container-fluid">
  <div class="row">
    <%= render :partial => "wtbooks_subject_sidebar"%>
    <div id='pub_book'>  
    <div class="col-sm-8 col-md-9">
      <ul class="breadcrumb breadcrumb2 print">
        <%= link_to "Home", homes_path%> &gt; Authors
      </ul>
      <div class="border_wrapper padding10px">
        <div class="">
          <h1 class="text_uppercase border_bottom heading-main text-uppercase "> AUTHOR(S):</h1>
        </div>       
        <div class="text_uppercase  border_bottom padding_bottom12px">
          <div class="col-sm-12 no-padd">
            <div class="ln-letters">
              <ul class="abc nomargin">
                <% ('A'..'Z').each do |letter| %> 
                  <li>
                    <%= link_to letter, get_author_homes_path(:letter=>letter)%>
                  </li>
                <%end%>
              </ul>
              <div class="clearfix ln-last"></div>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>
        <%if @authors.present?%>
          <%@authors.each do |authname| %>
            <div class="col-md-12 no-padd">
              <ul id="demoOne" class="description margin_left5px">
                <li class="ln-K ln-k"><%= link_to truncate(authname, length: 14), books_by_author_homes_path(authname) %>
                </li>
              </ul>
            </div>
          <%end%> 
        <%end%>
      </div>
    </div>
    </div>
  </div>
</div>
<%= render :partial => "homes/publisher_footer"%>
<% end %>

app/views/shared/wtbooks/sign_in.html.erb
<%= render :partial => "#{@publisher.theme_name}"%> 

<div class="container-fluid">
  <div class="row">
    <%= render :partial => "wtbooks_subject_sidebar"%>
    <div id='pub_book'>  
    <div class="col-sm-8 col-md-9">
      <ul class="breadcrumb breadcrumb2 print"> 
        <%= link_to "Home", homes_path%> &gt; Login
      </ul>
      <div class="border_wrapper padding10px">
        <div class="">
          <h1 class="text_uppercase border_bottom heading-main ">Existing User Login</h1>
        </div>
        <p>Please login here or register below.</p>
        <div class="clearfix"></div>
        <div class=" col-sm-12 grayContainer pad20">
          <%= form_for(:session, url: login_homes_path, :html => {:class => 'form-horizontal col-sm-8'}) do |f| %>
            <div class="form-group">
              <label class="control-label col-sm-3" for="email"><%= f.label :email_address %>: <sup class="mandatory">*</sup></label>
              <div class="col-sm-9">
                <%= f.email_field :email, class: 'form-control', required: "true", placeholder: "Enter Email" %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-3" for="pwd"><%= f.label :password %>: <sup class="mandatory">*</sup></label>
              <div class="col-sm-9">
                <%= f.password_field :password, class: 'form-control', required: "true", placeholder: "Enter Password" %>          
              </div>
            </div>
            <div class="form-group">        
              <div class="col-sm-offset-3 col-sm-9">
                <%= f.submit "Login", class: "btn btn-inverse" %>
                <%= button_tag fa_icon("refresh", text: "Reset"), :class => "btn btn-default" ,type: :reset%>  
                <a data-backdrop="static" data-keyboard="false" data-toggle="" href="forgotPasswordPageHome.do">&nbsp;&nbsp;Forgot your Password?</a>
              </div>
            </div>
          </div>
        <% end %>
        <div class="col-sm-12 no-padd mt10">
          <h1 class="text_uppercase border_bottom heading-main ">NEW USER REGISTRATION</h1>
          <p>If you are a new user and have not yet registered, 
            <strong>please&nbsp;<%= link_to "register now", registration_homes_path, :class => "ulink" %>
            </strong>.</p>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
<%= render :partial => "homes/wtbooks_footer"%>