config/routes.rb
Rails.application.routes.draw do

  get 'welcome/new'

  get 'welcome/index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :subject_group_books do 
    collection do
      get 'metadata_sheet'
      post 'import'
      post 'unassociate_books'
    end
  end
 mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
 
  get 'index_contents/content_code'

  get 'index_contents/publisher_code'

  get '/download_quote/:id', to: 'content_conversations#show', as: 'download_quote'

  get 'my_accounts/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :site_settings do 
    collection do 
      get 'books_of_publisher'
      get 'simple_search'
      get 'homepage'
      get 'new_homepage'
      patch 'update_homepage'
    end
  end

  get 'homes/index'
  root :to => "homes#index"
  get 'homes/search'
  get 'homes/subscribes_books'
  get 'homes/institution_edit'
  get 'homes/institution_profile_wta'

  resources :homes do
    collection do
      get  'permission_check_for_books'
      get  'books_by_category'
      get  'books_by_subject'
      get  'about'
      get  'terms_and_conditions'
      get  'policy'
      post 'wt_books_description' 
      get 'books_description'
      get 'wt_categories'
      get 'advance_search'
      get 'books_by_title'
      post 'send_mail'
      get 'refine_search'
      get 'refine_publishers_book'
      get 'refine_search_by_subject'
      get 'get_search_results'
      get 'get_author'
      get 'books_by_author'
      get 'contact'
      get 'catalogue'
      get 'download_file'
      get 'search'
      get 'sign_in'
      post 'login'
      get 'registration'
      post 'sign_up'
      delete 'logout'
      get 'current_user'
      get 'my_profile'
    end
  end

  resources :subject_groups do 
    collection do 
      get 'associate_book'
      get 'unassociate_book'
      post 'import'
      get 'metadata_sheet'
      get 'search'      
    end
  end 
 
  resources :contacts
  resources :subjects do
    collection do
      get 'search'
      post 'import'
      get 'metadata_sheet'
    end
  end

  resources :reports, :printhouse_setup, 
             only: [:index]
  resources :books_seo_config,:books_content_access_rules,
            :books_content_pricing, :books_contributors 
  resources :institution_accounts do
    collection do 
      get 'search'
      get 'add_subscription'
      post 'add_subscription_tag'
      get 'institution_admin_result'
      get 'metadata_for_institution_accounts'
      get 'metadata_for_institution_accounts_billing'
      get 'metadata_for_ip_address'
      post 'import_for_institution_accounts'
      post 'import_for_institution_accounts_billing'
      post 'import_for_ip_address'
    end
  end

  resources :library_users do 
    collection do
      get 'result'
    end
  end

  resources :articles do 
    collection do
      get 'search'
      get 'metadata_sheet'
    end
  end

  devise_for :users
  
  # devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'users/sign_in'

  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  resources :retailers do 
    collection do
      get 'search'
      get 'result'
    end
  end

  resources :end_users, :admin_users do 
    collection do
      get  'search' 
      get  'metadata_sheet'
      post 'import_for_end_users'
      # post 'create'
    end
  end

  resources :content_conversations do
    collection do 
      get 'content_history'
      get 'index_content'
      get 'qa_check'
      get 'update_status'
      get 'uploaded_errors'
      get 'dashboard'
      get 'download_books'
      get 'download_article'
      get 'download_update_status'
      get 'download_index_content'
      get 'download_subject_group'
    end
  end
  
  resources :subscriptions do
    collection do
      get 'view'
      post 'link'
      post 'save'
      get 'search'
      get 'content_search'
      get 'metadata_sheet'
      get 'search_result'
      get 'apply_discount'
      get 'result'
      get 'linked_member_publisher'
      get 'subject_group_search'
      get 'title_search'
      get 'associate_subscription_with_books'
      get 'associate_subscription_with_institutes'
      post 'import_for_subscription_institute'
      post 'import_for_subscription'
      post 'import'
    end
  end

  resources :publishers, :access_tokens, :promo_codes, :campaigns, :license_groups, :licenses,
            :subscriptions, :member_publishers do 
    collection do 
      post 'save'
      get 'search'
      get 'content_search'
      get 'metadata_sheet'
      get 'search_result'
      get 'apply_discount'
      get 'result'
      get 'linked_member_publisher'
      get 'subject_group_search'
      get 'title_search'
    end
  end
  
  resources :journals do
    collection do
      get 'index'
      get 'search'
      get 'search_result'  
    end
  end

  resources :books do
    collection do
      post 'save'
      get 'search'
      get 'metadata_sheet_for_books_primary_information'
      get 'metadata_sheet_for_books_contributor'
      get 'onix_input'
      get 'onix_supp_sheet'
      post 'import'
      post 'import_contributor'
      post 'import_chapter_details'
      delete 'destroy'
    end
  end

  resources :institution_admin_users do 
    collection do 
      get 'search'
    end
  end

  resources :themes do 
    collection do
      post 'save' 
      get 'change_theme'
      post 'save_theme_for_publisher'
      delete 'destroy'
    end
  end
end

app/views/shared/mlbooksinternational/about.html.erb
<section class="content">
    <!--Header-->
      <%= render :partial => "#{@publisher.theme_name}"%> 
    <!--HeaderEnd-->

    <div class="container-fluid">

      <div class="row">

        <div class='container'>
       
          <div id= 'pub_book'>
            
            <!-- about -->

            <div class="row"> 
              <div class="col-sm-12">
	              <div class="border_wrapper padding10px mt5">
	                <h1 class="heading1 sectionHeading border_bottom ">About Us</h1>
                  <div class="clearfix"></div>
		              <% if @publisher_about.present? %>
		                 <p class="mt20"><%= @publisher_about.html_safe %></p>
		              <%end%>
	              </div>
	            </div>
            </div>

            <!-- about end -->

          </div>
              
        </div>

      </div>
    </div>

    <footer>
      <%= render :partial => "homes/publisher_footer"%>
    </footer>
  
 
</section>      

app/views/shared/mlbooksinternational/books_by_author.html.erb
<section class="content">
  <!--Header-->
  <%= render :partial => "#{@publisher.theme_name}"%> 
  <!--HeaderEnd-->
  <div class="container-fluid">
    <div class="row">
      <div class='container'>
        <div class="border_wrapper padding10px mt5">
          <div id="bodydivs">
            <div id= 'pub_book'>
              <div class="row">
                <div class="col-sm-12">
                  <h3 class="heading1">Book Title</h3>
                  <div class="border_bottom"></div>
                  <div class="clearfix"></div>
                  <div class="col-sm-12 no-pad mt-20">
                    <nav aria-label="Page navigation"  >
                      <ul class='pagination pagination-sm'>
                        <div class="col-sm-4 pb-10">Search Results</div>
                          <div class="text-right col-sm-8">
                            <%= form_tag refine_publishers_book_homes_path, :method => 'get',:id=>"Author Name/Book Title",:class=>"form-inline pull-right",:remote=> true do %>
                              <div class="form-group">
                                <%= text_field_tag :book_title,"", :class => "form-control input-sm", :placeholder => "Refine Search" %>
                                <%= hidden_field_tag "book_ids", @ids  %>
                              </div>
                              <%= button_tag fa_icon("search", text: "Search"), :class => "btn btn-primary btn-sm responsive_margin_top20px border_radius3px", type: :submit %>
                            <%end%>
                          </div>
                          <div class="col-md-12 col-xs-12 mt-20">
                            <% if @books.count >= 0 %>
                              <div class="bg-gray">
                                <div class="col-sm-4 no-pad" style="padding-top: 6px;"> 
                                  <%= page_entries_info @books %>
                                </div>
                                <div class="col-sm-8 text-right no-pad">
                                  <div class="pagination-frontend" id="sresult">
                                    <nav aria-label="Page navigation" style="clear:both;"> 
                                      <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                                    </nav>  
                                  </div>
                                </div>
                                <div class="clearfix"></div>
                              </div>
                            <%end%>
                          </div>
                          <div class="clearfix"></div>
                          <% if @books.present? %>
                            <% @books.each do |f| %>
                              <div class="col-md-12  no-pad mt-20">
                                <div class="col-md-2  col-sm-2 col-xs-12 ">
                                  <div class="effects search-result "> 
                                    <%= link_to image_tag("http://www.#{@publisher.domain_name}.com/static/templates/template1/#{@publisher.publisher_code}/thumbnails/#{f.isbn}-T-FC.jpg",class: "img-responsive"), books_description_homes_path(:book_id => f.id), class: "cover2" %>
                                  </div>
                                </div>
                                <div class="col-md-10">
                                  <div class="">
                                    <h2>
                                     <%= link_to f.book_title.presence || "", books_description_homes_path(:book_id => f.id) %>
                                    </h2>
                                    <h3>By :<span class="dark_yellow"><% f.books_contributors.each do |book_contributor| %>
                                      <%= truncate(book_contributor.first_name.presence || "" +" "+book_contributor.last_name.presence || "", length: 14)%>
                                    <%end%></span>
                                    </h3>
                                    <p><strong>
                                      Description
                                      :</strong> 
                                        <%= truncate(f.book_blurb.presence || "", length: 182) %>
                                        <%= link_to 'more', '', :class => "read-more-#{f.id}" %>
                                        <script>
                                          $('.read-more-<%= f.id %>').on('click', function(e) {
                                            e.preventDefault()
                                            $(this).parent().html('<strong> Description:</strong> <%= f.book_blurb %>')
                                          })
                                        </script>
                                     </p>
                                  </div>
                                </div>  
                              </div>
                              <div class="col-md-12 ">
                                <div class="border_bottom-list"></div>
                              </div>
                            <% end%>
                          <%else%>
                            <div class="container">
                              <div class="col-md-12">
                                <h3> Record Not Found </h3>
                              </div>
                            </div>
                          <%end%>
                           <!--lower pagination start -->
                          <div class="col-md-12 col-xs-12 mt-20">
                            <% if @books.count >= 0%>
                              <div class="bg-gray">
                                <div class="col-sm-4 no-pad" style="padding-top: 6px;"> 
                                  <%= page_entries_info @books %>
                                </div>
                                <div class="col-sm-8 text-right no-pad">
                                  <div class="pagination-frontend" id="sresult">
                                    <nav aria-label="Page navigation" style="clear:both;"> 
                                      <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                                    </nav>  
                                  </div>
                                </div>
                                <div class="clearfix"></div>
                              </div>
                            <%end%>
                          </div>
                        </div>
                      </ul>
                    </nav>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer class="footer">
    <%= render :partial => "homes/publisher_footer"%>
  </footer>
</section>    

app/views/shared/mlbooksinternational/books_by_category.html.erb
<section class="content">
  <!--Header-->
  <%= render :partial => "#{@publisher.theme_name}"%> 
  <!--HeaderEnd-->

  <div class="container-fluid">  
    <div class='container'>
      <div id= 'pub_book'>
            
            <!-- Category -->

            
    <div class="row">
      <div class="col-sm-12">
        <div class="border_wrapper padding10px mt5">
          <div id="bodydivs">
            <div class="col-sm-4 nopadding">
              <h3 class="heading1">Search Results</h3>
            </div>
            <div class="text-right col-sm-8 nopadding">
              <%= form_tag  refine_search_homes_path, :method => 'get',:id=>"Author Name/Book Title",:class=>"form-inline pull-right",:remote => true do %>
                <div class="form-group">
                  <%= text_field_tag :search,"", :class => "form-control input-sm", :placeholder => "Refine Search" %>
                  <%= hidden_field_tag :subject_group_id, @subject_group.id%>
                </div>
                <%= button_tag fa_icon("search", text: "Search"), :class => "btn btn-primary btn-sm responsive_margin_top20px border_radius3px", type: :submit %>
               <%end%>
            </div>
            <div class="clearfix"></div>
            <div class="col-md-12  nopadding  bg-gray mt20">
              <div class="pull-right">
                <div class="pagination pagination-sm nomargin">
                  <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                </div>
              </div>
            </div>
            <% if @books.present? %>  
              <% @books.each do |f| %>
              <div class="margin_top20px im_width">
                <div class="col-md-2  col-sm-2 col-xs-12 ">
                  <div class="effects search-result">
                    <a href="/#" class="cover2"><%= link_to image_tag("http://www.#{@publisher.domain_name}.com/static/templates/template1/#{@publisher.publisher_code}/thumbnails/#{f.isbn}-T-FC.jpg",class: "img-responsive"), books_description_homes_path(:book_id => f.id), class: "cover2" %></a>
                  </div>
                </div>
                <div class="col-md-10">
                  <h3 title=""><a href="#"><%= link_to truncate(f.book_title.presence || "", length: 14), books_description_homes_path(:book_id => f.id) %></a></h3>
                  <h3 title="Austin Balfour"> By
                    : <span class="dark_yellow"><% f.books_contributors.each do |book_contributor| %>
                          <%= book_contributor.first_name.presence || ""%>&nbsp<%= book_contributor.last_name.presence || ""%>
                        <%end%></span></h3>
                  <p>
                    <strong>Description :</strong>   
                      <%= truncate(f.book_blurb.presence || "", length: 182) %>
                      <%= link_to 'more', '', :class => "read-more-#{f.id}" %>
                      <script>
                        $('.read-more-<%= f.id %>').on('click', function(e) {
                          e.preventDefault()
                          $(this).parent().html('<strong> Description:</strong> <%= f.book_blurb %>')
                        })
                      </script>
                   </p>
                </div>
              </div>
              <% end %>
            <% else %> 
              <div class="container">
               <div class="col-md-12">
                 <h3> Record Not Found </h3>
                </div>
              </div>
            <%end%>
            <div class="border_bottom"></div>
            <div class="clearfix"></div>
            <div class="col-md-12  nopadding  bg-gray mt20">
              <div class="pull-right">
                <div class="pagination pagination-sm nomargin">
                  <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                </div>
              </div>
            </div>
            <div class=" clearfix"> </div>
          </div>
        </div>
      </div>
    </div>

            <!-- Category end -->

          </div>
      </div>
    </div>

    <footer>
      <%= render :partial => "homes/publisher_footer"%>
    </footer>
  
 
</section>      

app/views/shared/mlbooksinternational/books_by_title.html.erb
<section class="content">
    <!--Header-->
      <%= render :partial => "#{@publisher.theme_name}"%> 
    <!--HeaderEnd-->

    <div class="container-fluid">

      <div class="row">

        <div class='container'>
       
          <div id= 'pub_book'>
            
            <!-- title -->

            
            <div class="row">
              <div class="col-sm-12">
    <div class="border_wrapper padding10px mt5">
      <div id="bodydivs">
        <h3 class="heading1">Book Title</h3>
        <div class="border_bottom"></div>
        <div class="clearfix"></div>
        <div class="col-sm-12 no-pad mt-20">
          <nav aria-label="Page navigation"  >
            <ul class='pagination pagination-sm'>
              <li><%= link_to "All", books_by_title_homes_path %></li> 
              <% ('A'..'Z').each do |letter| %> 
                <li>
                  <%= link_to letter, books_by_title_homes_path(:letter=>letter)%>
                </li>
              <%end%>
            </ul>
          </nav>
        </div>
        <div class="clearfix"> </div>
        <% if @books.count >= 0 %>
          <div class="col-md-12  bg-gray mt20">
            <div class="pull-left mt5">
              <%= page_entries_info @books %>
            </div>
            <div class="pull-right bottomUl">
              <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
            </div>
           <div class="clearfix"></div>
          </div>
        <%end%>
         
        <% @books.each do |f| %>
          <div class="margin_top20px im_width">
            <div class="col-md-2  col-sm-2 col-xs-12 ">
              <div class="effects search-result">
                <%= link_to image_tag("http://www.#{@publisher.domain_name}.com/static/templates/template1/#{@publisher.publisher_code}/thumbnails/#{f.isbn}-T-FC.jpg",class: "img-responsive"), books_description_homes_path(:book_id => f.id), class: "cover2" %>
              </div>
            </div>
            <div class="col-md-10">
              <h3 title=""><%= link_to f.book_title, books_description_homes_path(:book_id => f.id) %></h3>
              <h3>By :<span class="dark_yellow"><% f.books_contributors.uniq.each do |book_contributor| %>
                  <%= book_contributor.first_name.presence || ""%>&nbsp<%= book_contributor.last_name.presence || ""%>
                <%end%></span></h3>
              <p><strong>Description :</strong>
                     <%= truncate(f.book_blurb.presence || "", length: 182) %>
                    <%= link_to 'more', '', :class => "read-more-#{f.id}" %>
                    <script>
                      $('.read-more-<%= f.id %>').on('click', function(e) {
                        e.preventDefault()
                        $(this).parent().html('<strong> Description:</strong> <%= f.book_blurb %>')
                      })
                    </script>
               </p>
              <h3></h3>
            </div>
            <div class=" clearfix"></div>
          </div>
          <div class="border_bottom"></div>
          <div class="clearfix"></div>
        <% end %>
          <% if @books.count >= 0 %>
            <div class="col-md-12  bg-gray mt20">
              <div class="pull-left mt5">
                <%= page_entries_info @books %>
              </div>
              <div class="pull-right bottomUl">
                 
                  <%= will_paginate @books,renderer: BootstrapPagination::Rails%>
                 
              </div>
            </div>
          <%end%>
            <div class=" clearfix"> </div>
        
      </div>
    </div>
  </div>
</div>

            <!-- title end -->

          </div>
              
        </div>

      </div>
    </div>

    <footer>
      <%= render :partial => "homes/publisher_footer"%>
    </footer>
  
 
</section>
<script>
  $('ul.pagination li').each(function() {
    if($(this).text().trim()== "<%= @letter%>"){
     $(this).addClass("active");
    }
  });
</script>    

app/views/shared/mlbooksinternational/books_description.html.erb
<section class="content">
    <!--Header-->
      <%= render :partial => "#{@publisher.theme_name}"%> 
    <!--HeaderEnd-->

    <div class="container-fluid">

      <div class="row">

        <div class='container'>
       
          <div id= 'pub_book'>
            
            <!-- DESCRIPTION -->

             <div id="bodydivs"> 
  <div class="row">
    <div class="col-md-12 mt20">
      <ul class="nav nav-tabs noborder" data-tabs="tabs" style="background: transparent;">
        <li class="active tabGradient"><a href="#bookInfo" data-toggle="tab">Book Info</a></li>
      </ul>
      <div class="tab-content tab_border grayContainer">
        <div class="tab-pane active" id="bookInfo">
          <div class="pageHeading">
            <h1> <a><strong><%= @book_information.book_title.presence || "" %></strong></a> </h1>
          </div>
          <div class="xtraPadding mt20">
            <div class="col-md-3 col-sm-3"> <%= image_tag("http://www.#{@publisher.domain_name}.com/static/templates/template1/#{@publisher.publisher_code}/thumbnails/#{@book_information.isbn}-T-FC.jpg",class: "img-responsive") %> 
            </div>
            <div class="col-md-9 col-sm-9"> 
                <!-- <p>To read sections of the book, please use the navigation menu at the top left.</p> -->
            <div class="clearFloat"></div>

            <p><span class="book_atr col-xs-12 col-md-3"><strong>ISBN&nbsp;:&nbsp;</strong></span><span class="book_description col-xs-12 col-md-9"><%= @book_information.isbn.presence || "" %></span></p>
            <p><span class="book_atr col-xs-12 col-md-3"><strong>Publisher&nbsp;:&nbsp;</strong></span> <span class="col-xs-12 book_description col-md-9">&nbsp;<%= @publisher.publisher_name.presence || "" %></span></p>
            <p><span class="book_atr col-xs-12 col-md-3"><strong>Language&nbsp;:&nbsp;</strong></span> <span class="col-xs-12 book_description col-md-9">&nbsp;<%= @book_information.language.presence || "" %></span></p>
            <% unless @book_information.subject_groups.blank? %>
              <p><span class="book_atr col-xs-12 col-md-3"><strong>Category&nbsp;:&nbsp;</strong></span> <span class="book_description col-xs-12 col-md-9">&nbsp;<%= @book_information.subject_groups.first.subject_group_name.presence || "" %></span></p>
            <% end %>

            <% unless @book_information.publication_date.blank? %>     
              <p><span class="book_atr col-xs-12 col-md-3"><strong>Publication Year&nbsp;:&nbsp;</strong></span> <span class="col-xs-12 book_description col-md-9">&nbsp;<%= @book_information.publication_date.to_date.year.presence || "" %></span></p>
            <%end%>
            <p><span class="book_atr col-xs-12 col-md-3"><strong>Price&nbsp;:</strong></span><span class="book_description col-xs-12 col-md-9">&nbsp;USD&nbsp; <%=number_with_precision(@book_information.book_price, :precision => 2) %>   </span></p>

            <% if @book_information.books_content_pricing.present? %>
              <p><span class="book_atr col-xs-12 col-md-3"><strong>Format&nbsp;:</strong></span><span class="col-xs-12 book_description col-md-9">&nbsp; <%=@book_information.books_content_pricing.format.presence || "" %></span></p>
            <% end %>
            <p><span class="book_atr col-xs-12 col-md-3"><strong>Description&nbsp;:&nbsp;</strong></span> <span class="col-xs-12 book_description col-md-12 margin_bottom10px"><%= @book_information.book_blurb.presence || "" %> </span></p>
            <p><span class="col-xs-12 book_atr col-md-3"><strong>Author/Editor&nbsp;:&nbsp;</strong></span> <span class="col-xs-12 book_description col-md-12">
              <% @book_information.books_contributors.uniq.each do |book_contributor| %>
                <%= book_contributor.first_name.presence || ""%>&nbsp<%= book_contributor.last_name.presence || ""%>
              <%end%>
             <br>
            </span></p>
            <p><span class="col-xs-12 book_atr col-md-3"><strong>Author's Description&nbsp;:&nbsp;</strong></span> <span class="col-xs-12 book_description col-md-12">
              <%= @book_information.books_contributors.first.description.presence || "" %>
             <br>
            </span></p>
          </div>
        </div>
      </div>
    </div>

    </div>
  </div>
</div>


            <!-- DESCRIPTION END -->

          </div>
              
        </div>

      </div>
    </div>

    <footer>
      <%= render :partial => "homes/publisher_footer"%>
    </footer>
  
 
</section>      

app/views/shared/mlbooksinternational/contact.html.erb
<section class="content">
    <!--Header-->
      <%= render :partial => "#{@publisher.theme_name}"%> 
    <!--HeaderEnd-->

    <div class="container-fluid">

      <div class="row">

        <div class='container'>
       
          <div id= 'pub_book'>
            
            <!-- Contact -->

            <div class="border_wrapper padding10px mt5">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="heading1 border_bottom">Contact Us</h1>
        <div class="col-sm-12 form_bg no-pad mt20">
          <div class="col-sm-8">
            <p>Please Fill Below Query Form, We'll right back soon with a response.</p>
            <p><em>Fields marked with <sup class="mandatory">*</sup>are compulsory</em></p>
            <br>
            <form action="search.do" method="get" id="advanceSearchForm" class="form-horizontal ">
              <%= form_tag(send_mail_homes_path) do %>
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <fieldset>
                  <div class="form-group  ">
                    <label class="col-md-3 control-label" for=""> Your name: <sup class="mandatory">*</sup></label>
                    <div class="col-md-6">
                      <%= text_field_tag :name,"", :class => "form-control" %>
                    </div>
                  </div>
                  <div class="form-group  mt-20">
                    <label class="col-md-3 control-label" for=""> Your email: <sup class="mandatory">*</sup></label>
                    <div class="col-md-6">
                      <%= text_field_tag :email,"", :required => true ,:class => "form-control" %>
                    </div>
                  </div>
                  <div class="form-group  mt-20">
                    <label class="col-md-3 control-label" for=""> Subject:</label>
                    <div class="col-md-6">
                      <%= text_field_tag :subject,"", :class => "form-control" %>
                    </div>
                  </div>
                  <div class="form-group  mt-20">
                    <label class="col-md-3 control-label" for=""> Your message: <sup class="mandatory">*</sup> </label>
                    <div class="col-md-6">
                      <%= text_area_tag :message,"", :class => "form-control", :maxlength => "140", :rows => "7" %>
                    </div>
                  </div>
                  <div class="form-group  mt-20">
                    <label class="col-md-3"> &nbsp;</label>
                    <div class="col-md-6">
                      <%= button_tag fa_icon("send Message", text: "Send Message"), :class => "btn btn-primary", type: :submit %>
                    </div>
                  </div>
                </fieldset>
              <% end %>
            </form>
          </div>
          <div class="col-sm-4">
            <div class="contact">      
              <h4 class="text_uppercase heading">ADDRESS</h4>
              <p><%= @publisher.publisher_address.presence || "" %>
              Email-<%= link_to @publisher.contact_email, "mailto:#{@publisher.contact_email}"%>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

            <!-- Contact end -->

          </div>
              
        </div>

      </div>
    </div>

    <footer>
      <%= render :partial => "homes/publisher_footer"%>
    </footer>
  
 
</section>      

app/views/shared/mlbooksinternational/get_author.html.erb
<section class="content">
    <!--Header-->
      <%= render :partial => "#{@publisher.theme_name}"%> 
    <!--HeaderEnd-->

    <div class="container-fluid">

      <div class="row">

        <div class='container'>
       
          <div id= 'pub_book'>
            
            <!-- GET Author -->

                 
            <div class="row">
  <div class="col-sm-12">
    <h1 class="heading1 border_bottom ">AUTHOR(S):</h1>
    <div class="mt20 border_bottom ">
      <ul class='pagination pagination-sm'>
        <% ('A'..'Z').each do |letter| %> 
          <li>
            <%= link_to letter, get_author_homes_path(:letter=>letter)%>
          </li>
        <%end%>
      </ul>
    </div>
    <div class="clearfix m-b-30"></div>
    <%if @authors.present?%>
      <%@authors.each do |authname| %>
        <div class="mt20 nopadding">
          <ul id="demoOne" class="description   margin_left5px">  
            <li class="ln-R ln-r">
              <%= link_to truncate(authname, length: 14), books_by_author_homes_path(authname) %>
            </li>
          </ul>
        </div>
      <%end%>
    <%end%>
  </div>
  <div class="clearfix"></div>
  </div>
 </div>
            <!-- End Author -->

          </div>
              
        </div>

      </div>
    </div>

    <footer>
      <%= render :partial => "homes/publisher_footer"%>
    </footer>
  
 
</section> 
<script>
  $('ul.pagination li').each(function() {
    if($(this).text().trim()== "<%= @letter%>"){
     $(this).addClass("active");
    }
  });
</script>      