config/routes.rb
Rails.application.routes.draw do

  get 'welcome/new'

  get 'welcome/index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :subject_group_books do 
    collection do
      get 'metadata_sheet'
      post 'import'
      post 'unassociate_books'
    end
  end
 mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
 
  get 'index_contents/content_code'

  get 'index_contents/publisher_code'

  get '/download_quote/:id', to: 'content_conversations#show', as: 'download_quote'

  get 'my_accounts/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :site_settings do 
    collection do 
      get 'books_of_publisher'
      get 'simple_search'
      get 'homepage'
      get 'new_homepage'
      patch 'update_homepage'
    end
  end

  get 'homes/index'
  root :to => "homes#index"
  get 'homes/search'
  get 'homes/subscribes_books'
  get 'homes/institution_edit'
  get 'homes/institution_profile_wta'

  resources :homes do
    collection do
      get  'permission_check_for_books'
      get  'books_by_category'
      get  'books_by_subject'
      get  'about'
      get  'terms_and_conditions'
      get  'policy'
      post 'wt_books_description' 
      get 'books_description'
      get 'wt_categories'
      get 'advance_search'
      get 'books_by_title'
      post 'send_mail'
      get 'refine_search'
      get 'refine_publishers_book'
      get 'refine_search_by_subject'
      get 'get_search_results'
      get 'get_author'
      get 'books_by_author'
      get 'contact'
      get 'catalogue'
      get 'download_file'
      get 'search'
      get 'sign_in'
      post 'login'
      get 'registration'
      post 'sign_up'
      delete 'logout'
      get 'current_user'
      get 'my_profile'
    end
  end

  resources :subject_groups do 
    collection do 
      get 'associate_book'
      get 'unassociate_book'
      post 'import'
      get 'metadata_sheet'
      get 'search'      
    end
  end 
 
  resources :contacts
  resources :subjects do
    collection do
      get 'search'
      post 'import'
      get 'metadata_sheet'
    end
  end

  resources :reports, :printhouse_setup, 
             only: [:index]
  resources :books_seo_config,:books_content_access_rules,
            :books_content_pricing, :books_contributors 
  resources :institution_accounts do
    collection do 
      get 'search'
      get 'add_subscription'
      post 'add_subscription_tag'
      get 'institution_admin_result'
      get 'metadata_for_institution_accounts'
      get 'metadata_for_institution_accounts_billing'
      get 'metadata_for_ip_address'
      post 'import_for_institution_accounts'
      post 'import_for_institution_accounts_billing'
      post 'import_for_ip_address'
    end
  end

  resources :library_users do 
    collection do
      get 'result'
    end
  end

  resources :articles do 
    collection do
      get 'search'
      get 'metadata_sheet'
    end
  end

  devise_for :users
  
  # devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'users/sign_in'

  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  resources :retailers do 
    collection do
      get 'search'
      get 'result'
    end
  end

  resources :end_users, :admin_users do 
    collection do
      get  'search' 
      get  'metadata_sheet'
      post 'import_for_end_users'
      # post 'create'
    end
  end

  resources :content_conversations do
    collection do 
      get 'content_history'
      get 'index_content'
      get 'qa_check'
      get 'update_status'
      get 'uploaded_errors'
      get 'dashboard'
      get 'download_books'
      get 'download_article'
      get 'download_update_status'
      get 'download_index_content'
      get 'download_subject_group'
    end
  end
  
  resources :subscriptions do
    collection do
      get 'view'
      post 'link'
      post 'save'
      get 'search'
      get 'content_search'
      get 'metadata_sheet'
      get 'search_result'
      get 'apply_discount'
      get 'result'
      get 'linked_member_publisher'
      get 'subject_group_search'
      get 'title_search'
      get 'associate_subscription_with_books'
      get 'associate_subscription_with_institutes'
      post 'import_for_subscription_institute'
      post 'import_for_subscription'
      post 'import'
    end
  end

  resources :publishers, :access_tokens, :promo_codes, :campaigns, :license_groups, :licenses,
            :subscriptions, :member_publishers do 
    collection do 
      post 'save'
      get 'search'
      get 'content_search'
      get 'metadata_sheet'
      get 'search_result'
      get 'apply_discount'
      get 'result'
      get 'linked_member_publisher'
      get 'subject_group_search'
      get 'title_search'
    end
  end
  
  resources :journals do
    collection do
      get 'index'
      get 'search'
      get 'search_result'  
    end
  end

  resources :books do
    collection do
      post 'save'
      get 'search'
      get 'metadata_sheet_for_books_primary_information'
      get 'metadata_sheet_for_books_contributor'
      get 'onix_input'
      get 'onix_supp_sheet'
      post 'import'
      post 'import_contributor'
      post 'import_chapter_details'
      delete 'destroy'
    end
  end

  resources :institution_admin_users do 
    collection do 
      get 'search'
    end
  end

  resources :themes do 
    collection do
      post 'save' 
      get 'change_theme'
      post 'save_theme_for_publisher'
      delete 'destroy'
    end
  end
end

app/models/subject_group.rb
class SubjectGroup < ApplicationRecord
	include Filterable # Search Module
	belongs_to :subject
	belongs_to :publisher
	has_many :subject_group_books
	has_many :subscriptions, through: :subscription_books
    has_many :books_primary_content_informations, through: :subject_group_books 
	# Validations
    validates_presence_of :publisher_id, :subject_group_code,
    :subject_group_name, :language
end

app/controllers/subject_groups_controller.rb
class SubjectGroupsController < ApplicationController
    before_action :authenticate_user!

  def new
    @subject_group = SubjectGroup.new
  end

  def edit
    @subject_group = SubjectGroup.find(params[:id])
    render 'new'
  end
  
  def create
    @subject_group = SubjectGroup.new(subject_group_params)
    if @subject_group.save
      redirect_to subject_groups_path
    else
      render 'new'
    end
  end

  def update
    @subject_group =SubjectGroup.find(params[:subject_group][:id])
    if @subject_group.update_attributes!(subject_group_params)
      # Handle a successful update.
      flash[:notice] = 'Subject Group successfully updated.'
      redirect_to subject_groups_path
    else
      render 'edit'
    end
  end

  def search
    @subject = Subject.all
    @subject_group = SubjectGroup.filter(params.slice(:publisher_id, :subject_group_name, :subject_group_code, :language))
  end

  def metadata_sheet
  end

  def import
    #  In this method,we get the entire Excel file in params.
    # in params[:file], we get the path of the excel file.
    spreadsheet = open_spreadsheet(params[:file])
    header = spreadsheet.row(1)
    # we fetch first row elements( that act as column names of table) in header
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      # we get excel's row elements(that are attributes of table) in header
      # and in spreadsheet.row(i) we get data for record
      # here we transpose inorder to map each column and data for record insertion
      @subject = SubjectGroup.new
      @subject.attributes = row.to_hash.slice(*row.to_hash.keys)
      if @subject.id.present?
       @subjects = SubjectGroup.find(@subject.id)
       @subjects.update_attributes!(@subject.attributes)
      else
       @subject.save!
      end
    end
    redirect_to :back
  end


  def open_spreadsheet(file)
     #  the details of Excel sheet are holded in file
    case File.extname(file.original_filename)
      # in file.original_filename, we get the name of the excel sheet.
      #  the File.extname is a method that is used to fetch the extension 
      # of file
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Spreadsheet.open(file.path, extension: :xls)
     # in file.path,we get the path in which the excel sheet is stored
     # Roo:Spreadsheet.open(file.path, extension: :xls) helps us to open the 
     # Excel Spreadsheet
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end


  def associate_book
    @subject_group_id = params[:subject_group_id]
    @subject_group_name = params[:subject_group_name]
    @books = BooksPrimaryContentInformation.where(:publisher_id => params[:format])
  end

  def unassociate_book
    @subject_group_id = params[:subject_group_id]
    @subject_group_name = params[:subject_group_name]
    @subject_group = SubjectGroup.find(params[:subject_group_id])
    @associated_books = @subject_group.books_primary_content_informations
  end

  private
  def subject_group_params
    params.require(:subject_group).permit(:publisher_id, :subject_group_level, 
    :subject_group_code, :subject_group_name, :guest_user_view_limit, :authentication_user_view_limit,
    :discount_percentage, :viewability_percentage, :language, :subject_group_description, :subject_id)
  end
end

app/helpers/subject_groups_helper.rb
module SubjectGroupsHelper
end

app/views/subject_groups/_search_result.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="mt10 table-demo">Search Result 
      <span class="pull-right">
        <div class="dropdown">
          <ul class="nav">
            <li class="drop"><i style="cursor: pointer;width: 12px;" class="fa fa-ellipsis-v" aria-hidden="true"></i>
              <ul class="dropdown-menu-right">
                <li><a href="#"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Excel</a></li>
                <li><a href="#"><i class="fa fa-file-o" aria-hidden="true"></i> CSV</a></li>
                <li><a href="#"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> PDF</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </span>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr style="font-size:13px">
            <th>Subject Name</th>
            <th>Subject Code</th>
            <th>Subject Level</th>
            <th>Action</th>
            <th>Action</th>
            <th>Edit</th>
          </tr>
        </thead>
        <tbody>
          <% if @subject_group.present? %>
	      		<% @subject_group.each do |f| %>
              <tr>
                <td><%= f.subject_group_name %></td>
                <td><%= f.subject_group_code %></td>
                <td><%= f.subject_group_level %></td>
                <td><%= link_to 'Associate Books',associate_book_subject_groups_path(f.publisher_id, subject_group_name: f.subject_group_name, subject_group_id: f.id) %></td>
                <td><%= link_to 'Unassociate Books',unassociate_book_subject_groups_path(f.publisher_id, subject_group_name: f.subject_group_name, subject_group_id: f.id) %></td>
                 <td><%= link_to("Edit ", edit_subject_group_path(f.id), :class => "btn btn-sm", :method => :get) %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td bgcolor="#FBFBFB">
                <p> Record Not Found </p> 
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-sm-12"> </div>
</div>

app/views/subject_groups/associate_book.html.erb
<!doctype html>
<html>
<head>
<title>Content Store :: Search Subject</title>
<!-- Latest compiled and minified CSS -->
    <!-- Header -->
   <%= render :partial => "layouts/top_header"%>
    <!-- Header Ends --> 
</head>

<body>
  <!-- Aside Start-->
    <%= render :partial => "layouts/sidebar"%>
    <!-- Aside Ends-->
  <!--Main Content Start -->
  <section class="content"> 
    <!-- Page Content Start --> 
    <!-- ================== -->
    <div class="wrapper container-fluid">
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a>Publisher Setup</a></li>
        <li><a>Associate Books</a></li>
      </ol>
      
      <h2 class="H2-L1">Associate Books</h2>
      <div class="wrapper container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="mt10 table-demo">
              Select books for "<%= @subject_group_name %>"
            </div>
            <div class="table-responsive">
              <%= form_tag subject_group_books_path, :method => 'post' do %>
                <table class="table table-bordered">
                  <thead>
                    <tr style="font-size:13px">
                      <th></th>
                      <th>Book Title</th>
                      <th>Book ISBN</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% if @books.present? %>
                      <% @books.each do |book| %>
                        <tr>
                          <td><%= check_box_tag "book_id[]", book.id %></td>
                          <td><%= book.book_title %></td>
                          <td><%= book.isbn %></td>
                        </tr>
                        <%= hidden_field_tag "subject_group_id", @subject_group_id %>
                      <% end %>
                    <% else %>
                      <tr>
                        <td bgcolor="#FBFBFB">
                          <p> Record Not Found </p> 
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <%= button_tag fa_icon("search", text: "Associate Books"), :class => "btn btn-sm", type: :submit %>
              <% end %>
            </div>
          </div>
          <div class="col-sm-12"></div>
        </div>
      </div>
    </div>  
    <!-- Footer Start -->
    <%= render :partial => "layouts/footer" %>
    <!-- Footer Ends --> 
  </section>
</body>
</html>

app/views/subject_groups/index.html.erb
<!doctype html>
<html>
<head>
<title>Content Store :: Search Subject</title>
<!-- Latest compiled and minified CSS -->
    <!-- Header -->
   <%= render :partial => "layouts/top_header"%>
    <!-- Header Ends --> 
</head>

<body>
  <!-- Aside Start-->
    <%= render :partial => "layouts/sidebar"%>
    <!-- Aside Ends-->
  <!--Main Content Start -->
  <section class="content"> 
    <!-- Page Content Start --> 
    <!-- ================== -->
    <div class="wrapper container-fluid">
      <ol class="breadcrumb">
         <li><a href="#">Home</a></li>
       <li><a> Publisher Setup</a></li>
       <li><a>Search Subject</a></li>
      </ol>
      
      <h2 class="H2-L1">Search Subject</h2>
      <%= form_tag search_subject_groups_path, :method => 'get', :remote => true do %>
        <div class="col-md-6">
          <div class="form-group">
            <label for="taskName" class="col-sm-4 control-label">Publisher</label>
            <div class="col-sm-8">
             <%= select_tag 'publisher_id',options_from_collection_for_select(publisher_names, 'id', 'publisher_name'), :prompt => "Select Publisher", :class => "form-control", :style => "background-color: #eee"%>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="bookISBN" class="col-sm-4 control-label">Subject Name</label>
            <span class="col-sm-8">
            <%= text_field_tag :subject_group_name, params[:subject_group_name],:class => "form-control", :placeholder => "Subject Name" %>
            </span> 
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="bookISBN" class="col-sm-4 control-label">Subject Code</label>
            <span class="col-sm-8">
            <%= text_field_tag :subject_group_code, params[:subject_group_code],:class => "form-control", :placeholder => "Subject Code" %>
            </span> 
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="bookISBN" class="col-sm-4 control-label">Select Language</label>
            <span class="col-sm-8">
            <%= select_tag 'language',options_for_select(['Dansk', 'Polish', 'Latvian','English']), :prompt => "Select Language", :class => "form-control", style: "background-color: #eee;" %>
            </span> 
            <div class="clearfix"></div>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="clearfix m-b-30"></div>
          <div class="col-lg-12 col-md-12 col-sm-12 colx-12 text-right">
            <%= button_tag fa_icon("search", text: "Search"), :class => "btn btn-sm", type: :submit %>
            <%= button_tag fa_icon("refresh", text: "Reset"), :class => "btnBlack btn-sm" ,type: :reset%>
          </div>
          <div class="clearfix m-b-30"></div>
          <div id="search_result"></div>
        </div>
      <%end%>
    </div>
    <!-- Page Content Ends --> 
    <!-- ================== --> 
  
    <!-- Footer Start -->
    <%= render :partial => "layouts/footer" %>
    <!-- Footer Ends --> 
  </section>
</body>
</html>

app/views/subject_groups/metadata_sheet.html.erb
<!doctype html>
<html>
<head>
<title>Content Store :: Upload Subject Metadata File  </title>
<!-- Latest compiled and minified CSS -->
  <!-- Header -->
  <%= render :partial => "layouts/top_header"%>
  <!-- Header Ends --> 
</head>

<body>
<!-- Aside Start-->
    <%= render :partial => "layouts/sidebar"%>
    <!-- Aside Ends-->
<!--Main Content Start -->
<section class="content"> 
  <!-- Page Content Start --> 
  <!-- ================== -->
  <div class="wrapper container-fluid">
  <ol class="breadcrumb">
       <li><a href="#">Home</a></li>
     <li><a href="#">Content Conversion</a></li>
     <li><a href="#" class="active">Upload Subject Metadata File</a></li>
        
      </ol>
    
    <h2 class="H2-L1">Upload Subject Metadata File</h2>
    <form class="form-horizontal form-bg" role="form">
            <%= form_tag metadata_sheet_subject_groups_path, :method => 'get' do %>
      
      <div class="col-md-12">
        <div class="form-group">
          <label for="bookISBN" class="col-sm-2 control-label">Select Language:</label>
          <span class="col-sm-4">
          <%= select_tag(:JOC_CODE, options_for_select([['Select',0],[' Dansk',1],['Polish',2],['Latvian',3],['English',4]]))  %>
          </span> 
        </div>
      </div>
    <div class="col-md-12">
        <div class="form-group">
          <label for="bookISBN" class="col-sm-2 control-label">File Name:</label>
          <span class="col-sm-4">
         <div class="file-placeholder">
             
            <input type="file" class="fileUpload" >
            
            <div class="file-browse">
              <input type="file" name="uploadMetadataFile" size="60" value="" onkeydown="return false;" onkeypress="return false;" id="uploadMetadataFile" class="text_field">
             <span class="file-browse-txt">Select somes files </span>
             <span class="browse">Browse</span>
            </div>
           </div>
          </span> 
     </div>
      </div>
      <%= submit_tag "Upload" %>
                <%= button_tag "Cancel", type: :reset %>
      <div class="clearfix"></div>
    </form>
    <div class="clearfix m-b-30"></div>
  <div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 colx-12 text-right">
  <button type="submit" class="btn btn-sm pull-left" data-toggle="modal" data-target="#createAdminUsers"><i class="fa fa-plus-square-o" aria-hidden="true"></i> &nbsp;<%= link_to 'Create Subject Group', new_subject_group_path %></button>
    
    <button type="submit" class="btn btn-sm" onclick="javascript:showDiv();"><i class="fa fa-cloud-download" aria-hidden="true"></i> &nbsp;<%= link_to 'Download Template', download_subject_group_content_conversations_path %></button>
    <button type="submit" class="btn btn-sm" onclick="javascript:showDiv();"><i class="fa fa-cloud-upload" aria-hidden="true"></i> &nbsp;Upload</button>
        <button type="reset" class="btnBlack btn-sm" onclick="javascript:hideDiv();"><i class="fa fa-refresh" aria-hidden="true"></i> &nbsp;Clear</button>
      </div>
    </div>
    <div class="clearfix m-b-30"></div>
  
      <% end %>
      <div class="col-sm-12"> </div>
  </div>
  <!-- Page Content Ends --> 
  <!-- ================== --> 
  
  <!-- Footer Start -->
  <%= render :partial => "layouts/footer"%>
  <!-- Footer Ends --> 
</section>

<!--for popup page all popup comes from this page-->
<!-- Main Content Ends --> 
<!-- Latest compiled and minified JavaScript --> 
 
 
<script type="text/javascript">
        function showDiv() {
            div = document.getElementById('searchResultGrid');
            div.style.display = "block";
        }
    function hideDiv() {
            div = document.getElementById('searchResultGrid');
            div.style.display = "none";
        }
    function hideshow() {
    var x = document.getElementById('addpublisher');
    if (x.style.display === 'none') {
        x.style.display = 'block';
    } else {
        x.style.display = 'none';
    }
}
    </script>
<!--Chart code end-->
</body>
</html>

app/views/subject_groups/search.js.erb
$("#search_result").html("<%= escape_javascript(render(:partial => "search_result", :object => @subject_group))%>");

app/views/subject_groups/unassociate_book.html.erb
<!doctype html>
<html>
<head>
<title>Content Store :: Search Subject</title>
<!-- Latest compiled and minified CSS -->
    <!-- Header -->
   <%= render :partial => "layouts/top_header"%>
    <!-- Header Ends --> 
</head>

<body>
  <!-- Aside Start-->
    <%= render :partial => "layouts/sidebar"%>
    <!-- Aside Ends-->
  <!--Main Content Start -->
  <section class="content"> 
    <!-- Page Content Start --> 
    <!-- ================== -->
    <div class="wrapper container-fluid">
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a>Publisher Setup</a></li>
        <li><a>Unassociate Books</a></li>
      </ol>
      
      <h2 class="H2-L1">Unassociate Books</h2>
      <div class="wrapper container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="mt10 table-demo">
              Select books for "<%= @subject_group_name %>"
            </div>
            <div class="table-responsive">
              <%= form_tag unassociate_books_subject_group_books_path, :method => 'post' do %>
                <table class="table table-bordered">
                  <thead>
                    <tr style="font-size:13px">
                      <th></th>
                      <th>Book Title</th>
                      <th>Book ISBN</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% if @associated_books.present? %>
                      <% @associated_books.each do |book| %>
                        <tr>
                          <td><%= check_box_tag "book_id[]", book.id %></td>
                          <td><%= book.book_title %></td>
                          <td><%= book.isbn %></td>
                        </tr>
                        <%= hidden_field_tag "subject_group_id", @subject_group_id %>
                      <% end %>
                    <% else %>
                      <tr>
                        <td bgcolor="#FBFBFB">
                          <p> Record Not Found </p> 
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <%= button_tag fa_icon("search", text: "Unassociate Books"), :class => "btn btn-sm", type: :submit %>
              <% end %>
            </div>
          </div>
          <div class="col-sm-12"></div>
        </div>
      </div>
    </div>  
    <!-- Footer Start -->
    <%= render :partial => "layouts/footer" %>
    <!-- Footer Ends --> 
  </section>
</body>
</html>